<?php
// Builds a static, read-only mirror of index.php as index.html: the book list, custom
// titles/page counts, and every text transcription (Oma/GPT/Digihakemisto), but no scanned
// PDFs and no save/edit endpoints - those need "php -S" to work, this page doesn't.
// Suitable for hosting on GitHub Pages or any plain static host.
//
// Run: php build.php

// books.json is the single source of truth: {"<id>": {category, dir, title, pages}}.
$meta = json_decode(file_get_contents(__DIR__ . "/books.json"), true);
if (!is_array($meta)) $meta = [];

// The static page never edits or shows the PDF, so it only needs these fields.
$staticBooks = [];
foreach ($meta as $id => $b) {
  $staticBooks[] = [
    "id" => (string)$id, // PHP casts numeric-looking JSON object keys to int; force back to string
    "category" => $b["category"],
    "title" => $b["title"] ?? "",
    "pages" => $b["pages"] ?? null,
    "fileData" => "books/" . $b["dir"] . "/" . $id . ".json",
  ];
}

$booksJson = json_encode($staticBooks, JSON_UNESCAPED_UNICODE);

$html = <<<'HTML'
<!DOCTYPE html>
<html lang="fi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Sukututkimus</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css">
<style>
  mark { background-color: #fcd34d; }
  pre { white-space: pre-wrap; font-family: ui-monospace, Menlo, Consolas, monospace; }
</style>
</head>
<body class="bg-yellow-50 text-gray-800 min-h-screen flex flex-col">

<header class="bg-yellow-900 text-yellow-50 border-b-4 border-yellow-600">
  <div class="px-6 py-6 flex flex-wrap items-center justify-between gap-4">
    <div>
      <h1 class="text-3xl font-serif font-bold"><a href="#" onclick="showList();return false" class="hover:text-yellow-200">Sukututkimus</a></h1>
      <p class="text-yellow-200 mt-1">Taipaleen ortodoksisen seurakunnan arkistokirjat</p>
    </div>
    <input id="search" type="text" placeholder="Hae... (voit käyttää * jokerimerkkinä)"
      class="w-full sm:w-80 border-2 border-yellow-400 rounded px-3 py-2 bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-yellow-500"
      onkeyup="search(this.value)">
  </div>
</header>

<div class="px-6 py-4 w-full flex-1">

  <div id="output">Ladataan...</div>

</div>

<footer class="border-t-2 border-yellow-500 mt-8">
  <div class="px-6 py-6 text-center text-sm text-gray-600">
    Tehnyt <a href="https://www.jukkapajarinen.com" class="text-yellow-800 underline hover:text-yellow-900" target="_blank" rel="noopener">Jukka Pajarinen</a>
    &middot; <a href="https://github.com/jukkapajarinen/sukututkimus" class="text-yellow-800 underline hover:text-yellow-900" target="_blank" rel="noopener">GitHub</a>
  </div>
</footer>

<script>
// Static snapshot: no PDFs, no save/edit endpoints. Generated by build.php - edit that
// script (or the live index.php) rather than this file, it gets overwritten on rebuild.
var BOOKS = __BOOKS_JSON__;

var output = document.getElementById("output");
var SOURCES = {
  mine: { label: "Oma", field: "textMine" },
  gpt: { label: "GPT", field: "textGpt" },
  digi: { label: "Digihakemisto", field: "textDigi" }
};
var viewMode = "list";

// Each book's transcriptions live in one books/<dir>/<id>.json ({gpt, mine, digi});
// a book with none of them yet has no file at all, so a 404 there is expected.
var fetches = [];
BOOKS.forEach(function (b) {
  fetches.push(
    fetch(b.fileData)
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data) {
        if (!data) return;
        if (data.gpt) b.textGpt = data.gpt;
        if (data.mine) b.textMine = data.mine;
        if (data.digi) b.textDigi = data.digi;
      })
      .catch(function () {})
  );
});
Promise.all(fetches).then(showList);

// Splits a transcript into { pageNumber: pageText } based on "[Sivu N]" headings.
// Falls back to putting everything on page 1 if no headings are found.
function pagesFromText(text) {
  var map = {};
  if (!text) return map;
  var re = /\[Sivu\s+(\d+)\]/g;
  var matches = [];
  var m;
  while ((m = re.exec(text))) matches.push({ num: parseInt(m[1], 10), start: m.index, end: re.lastIndex });
  if (!matches.length) { map[1] = text; return map; }
  matches.forEach(function (mm, i) {
    var contentStart = mm.end;
    var contentEnd = (i + 1 < matches.length) ? matches[i + 1].start : text.length;
    map[mm.num] = text.slice(contentStart, contentEnd).replace(/^\s+/, "").replace(/\s+$/, "");
  });
  return map;
}

// "<id> — <custom title>"; titles are read-only here (set via index.php, not this static page).
function titleSuffixHtml(b) {
  return b.title ? " <span class='font-normal text-gray-600'>&mdash; " + escapeHtml(b.title) + "</span>" : "";
}

// The PDF's page count, as cached (via index.php) in the book's JSON.
function pageCountSuffixHtml(b) {
  return b.pages ? " <span class='font-normal text-sm text-green-700'>(" + b.pages + " sivua)</span>" : "";
}

function showList() {
  viewMode = "list";
  var html = "";
  var lastCategory = null;
  BOOKS.forEach(function (b) {
    if (b.category !== lastCategory) {
      html += "<h2 class='font-serif font-semibold text-yellow-900 mt-6 mb-2'>" + b.category + "</h2>";
      lastCategory = b.category;
    }
    var links = "";
    if (b.textGpt) {
      links += "<a href='#' onclick='event.stopPropagation();showBookPage(\"" + b.id + "\", 1, \"gpt\", 0);return false' " +
        "class='text-xs font-bold uppercase tracking-wide px-2 py-0.5 rounded border-2 border-green-500 text-green-800 bg-green-50 hover:bg-green-100'>GPT</a>";
    }
    if (b.textMine) {
      links += "<span class='ml-3 text-xs font-bold uppercase tracking-wide px-2 py-0.5 rounded border-2 border-blue-500 text-blue-800 bg-blue-50'>Jukka Pajarinen</span>";
    }
    if (b.textDigi) {
      links += "<a href='#' onclick='event.stopPropagation();showBookPage(\"" + b.id + "\", 1, \"digi\", 0);return false' " +
        "class='ml-3 text-xs font-bold uppercase tracking-wide px-2 py-0.5 rounded border-2 border-purple-500 text-purple-800 bg-purple-50 hover:bg-purple-100'>Digihakemisto</a>";
    }
    html += "<div onclick='showBookPage(\"" + b.id + "\", 1)' " +
      "class='flex items-center justify-between bg-white border-2 border-yellow-400 rounded px-4 py-2 mb-1 text-yellow-900 cursor-pointer hover:bg-yellow-50'>" +
      "<span>" + b.id + pageCountSuffixHtml(b) + titleSuffixHtml(b) + "</span>" +
      "<span class='space-x-1'>" + links + "</span></div>";
  });
  output.innerHTML = html;
}

// Current page-viewer state.
var current = { book: null, page: 1, pageCount: 1, gptPages: {}, minePages: {}, digiPages: {} };

function showBookPage(id, page, focusSource, focusLineIndex) {
  var b = BOOKS.find(function (x) { return x.id === id; });
  if (!b) return;

  viewMode = "book";
  current.book = b;
  current.gptPages = pagesFromText(b.textGpt);
  current.minePages = pagesFromText(b.textMine);
  current.digiPages = pagesFromText(b.textDigi);

  var maxPage = 1;
  [current.gptPages, current.minePages, current.digiPages].forEach(function (pages) {
    Object.keys(pages).forEach(function (k) {
      var n = parseInt(k, 10);
      if (n > maxPage) maxPage = n;
    });
  });
  current.pageCount = maxPage;
  current.page = Math.min(page || 1, maxPage);

  output.innerHTML = bookPageShell(b);
  renderCurrentPage(focusSource, focusLineIndex);
}

function bookPageShell(b) {
  return "" +
    "<p class='mb-3'><a href='#' onclick='showList();return false' class='text-yellow-800 underline'>&larr; takaisin</a></p>" +
    "<h2 class='text-xl font-serif font-semibold mb-1 text-yellow-900'>" + b.id + titleSuffixHtml(b) + "</h2>" +
    "<p class='text-sm text-gray-600 mb-3'>" + b.category + "</p>" +
    "<div class='flex flex-wrap items-center gap-2 mb-4 bg-white border-2 border-yellow-400 rounded px-3 py-2'>" +
      "<button onclick='gotoPage(-1)' class='px-2 py-1 border-2 border-yellow-400 rounded hover:bg-yellow-50'>&larr; Edellinen</button>" +
      "<span>Sivu <input id='pageInput' type='number' min='1' value='" + current.page + "' " +
        "class='w-16 border-2 border-yellow-400 rounded px-1 text-center' onchange='gotoPageInput(this.value)'> / " +
        "<span id='pageCount'>" + current.pageCount + "</span></span>" +
      "<button onclick='gotoPage(1)' class='px-2 py-1 border-2 border-yellow-400 rounded hover:bg-yellow-50'>Seuraava &rarr;</button>" +
    "</div>" +
    "<div class='grid grid-cols-1 lg:grid-cols-3 gap-4'>" +
      "<div>" +
        "<h3 class='font-serif font-semibold text-blue-800 mb-1'>Oma transkriptio</h3>" +
        "<pre id='mineText' class='w-full border-4 border-blue-400 rounded p-2 text-sm bg-blue-50 overflow-auto' style='height:60vh'></pre>" +
      "</div>" +
      "<div>" +
        "<h3 class='font-serif font-semibold text-green-800 mb-1'>ChatGPT-transkriptio</h3>" +
        "<pre id='gptText' class='w-full border-4 border-green-400 rounded p-2 text-sm bg-green-50 overflow-auto' style='height:60vh'></pre>" +
      "</div>" +
      "<div>" +
        "<h3 class='font-serif font-semibold text-purple-800 mb-1'>Digihakemisto</h3>" +
        "<pre id='digiText' class='w-full border-4 border-purple-400 rounded p-2 text-sm bg-purple-50 overflow-auto' style='height:60vh'></pre>" +
      "</div>" +
    "</div>";
}

function renderCurrentPage(focusSource, focusLineIndex) {
  var pageInput = document.getElementById("pageInput");
  var pageCount = document.getElementById("pageCount");
  if (pageInput) pageInput.value = current.page;
  if (pageCount) pageCount.textContent = current.pageCount;

  var page = current.page;
  renderReadOnlyPane("mineText", current.minePages[page], "(ei omaa transkriptiota tälle sivulle)", focusSource === "mine", focusLineIndex);
  renderReadOnlyPane("gptText", current.gptPages[page], "(ei ChatGPT-transkriptiota tälle sivulle)", focusSource === "gpt", focusLineIndex);
  renderReadOnlyPane("digiText", current.digiPages[page], "(ei digihakemisto-tietoja tälle sivulle)", focusSource === "digi", focusLineIndex);
}

// Renders a read-only pane, highlighting one line when it's the search-jump target.
function renderReadOnlyPane(elId, text, emptyMessage, isFocused, focusLineIndex) {
  var el = document.getElementById(elId);
  if (!el) return;
  if (isFocused && focusLineIndex !== undefined && text !== undefined) {
    var lines = text.split("\n");
    el.innerHTML = lines.map(function (l, i) {
      var esc = escapeHtml(l);
      return i === focusLineIndex ? "<mark id='hit'>" + esc + "</mark>" : esc;
    }).join("\n");
    var hit = document.getElementById("hit");
    if (hit) hit.scrollIntoView({ behavior: "smooth", block: "center" });
  } else {
    el.textContent = text !== undefined ? text : emptyMessage;
  }
}

function gotoPage(delta) {
  if (!current.book) return;
  var next = current.page + delta;
  if (next < 1) next = 1;
  if (next > current.pageCount) next = current.pageCount;
  current.page = next;
  renderCurrentPage();
}

function gotoPageInput(value) {
  if (!current.book) return;
  var n = parseInt(value, 10);
  if (isNaN(n) || n < 1) n = 1;
  if (n > current.pageCount) n = current.pageCount;
  current.page = n;
  renderCurrentPage();
}

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Plain substring match, case-insensitive. A "*" in the query means "any characters here",
// e.g. "p*ari*" matches "pekka-ari-nen".
function matchesQuery(query, text) {
  query = query.toLowerCase();
  text = text.toLowerCase();
  if (query.indexOf("*") === -1) return text.indexOf(query) !== -1;
  var pattern = query.split("*").map(function (part) {
    return part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }).join(".*");
  return new RegExp(pattern).test(text);
}

function search(query) {
  if (!query) { showList(); return; }
  var html = "";
  BOOKS.forEach(function (b) {
    Object.keys(SOURCES).forEach(function (source) {
      var src = SOURCES[source];
      var text = b[src.field];
      if (!text) return;
      var pages = pagesFromText(text);
      var pageNums = Object.keys(pages).map(Number).sort(function (a, c) { return a - c; });
      var bookHits = [];
      pageNums.forEach(function (pn) {
        pages[pn].split("\n").forEach(function (l, i) {
          if (l.trim() && matchesQuery(query, l)) bookHits.push({ page: pn, lineIndex: i, text: l });
        });
      });
      if (bookHits.length) {
        html += "<h3 class='font-serif font-semibold mt-4 text-yellow-900'>" + b.id + " &middot; " + b.category + " &middot; " + src.label + "</h3><ul class='space-y-1'>";
        bookHits.forEach(function (h) {
          html += "<li><a href='#' onclick='showBookPage(\"" + b.id + "\", " + h.page + ", \"" + source + "\", " + h.lineIndex + ");return false' " +
            "class='block bg-white border-2 border-yellow-400 rounded px-3 py-1 text-sm text-gray-900 hover:border-yellow-600 hover:shadow transition'>" +
            "<span class='text-xs text-gray-700 mr-2'>s. " + h.page + "</span>" + escapeHtml(h.text) + "</a></li>";
        });
        html += "</ul>";
      }
    });
  });
  output.innerHTML = html || "<p class='text-gray-600'>Ei osumia.</p>";
}
</script>

</body>
</html>
HTML;

$html = str_replace("__BOOKS_JSON__", $booksJson, $html);

$outPath = __DIR__ . "/index.html";
file_put_contents($outPath, $html);
echo "Wrote " . $outPath . " (" . count($staticBooks) . " books, no PDFs/edit endpoints - static text-only mirror)\n";
